# Generated by Django 5.2.8 on 2026-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesection_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_lectures/'),
        ),
    ]
