# Generated by Django 5.2.8 on 2026-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lecture_video_url_alter_lecture_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lecture_pdfs/'),
        ),
    ]
