# Generated by Django 5.2.8 on 2026-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assessment_attempt_question_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
