# Generated by Django 5.2.8 on 2026-02-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_assessment_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
