# Generated by Django 5.2.8 on 2026-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_answer_answer_text_answer_marks_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded')], default='PENDING', max_length=20),
        ),
    ]
