# Generated by Django 5.2.8 on 2026-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_attempt_graded_at_attempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='live_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='live_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
