# Generated by Django 5.2.8 on 2026-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lecture_is_live_lecture_live_join_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='live_join_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='live_start_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
