# Generated by Django 5.2.8 on 2026-04-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lecture_live_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
