# Generated by Django 5.2.8 on 2026-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lecture_live_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
