# Generated by Django 5.2.8 on 2026-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lecture_duration_minutes_lecture_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
