# Generated by Django 5.2.8 on 2025-12-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
