# Generated by Django 5.2.8 on 2025-11-14 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('course_type', models.CharField(choices=[('COURSE', 'Course'), ('PRACTICE_TEST', 'Practice test')], default='COURSE', max_length=20)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('time_per_week', models.CharField(blank=True, max_length=120)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('video_url', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
