# Generated by Django 5.2.8 on 2025-11-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='video_file',
            new_name='intro_video_file',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='video_url',
            new_name='intro_video_url',
        ),
    ]
